version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/wxchat.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: wxchat
build:
  run_buildscript: false
images:
  - id: wxchat
    target: service
    service: wxchat
    source: yilan666/wxchat
    channel: custom
    sort: semver
    tag_regex: '^v?\d+\.\d+$'
    version_regex: '^v?(?P<version>\d+\.\d+)$'
    version_template: '{version}.0'
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
    changelog_locales: [zh, en]
  private:
    enabled: true
    skip_if_version_exists: true
    name: 文件传输助手
    summary: "类微信文件传输助手，能像微信聊天一样在手机、电脑、平板之间快速互传文件、图片、文字和链接。"
