min_os_version: 1.3.8
name: 文件传输助手
package: community.lazycat.app.wxchat
version: 5.0.0
description: "类微信文件传输助手，能像微信聊天一样在手机、电脑、平板之间快速互传文件、图片、文字和链接。需要的话还可接入大模型做 AI 聊天/ 画图。"
homepage: https://github.com/DEKVIW/docker-wxchat
author: DEKVIW
application:
  subdomain: wxchat
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://wxchat:3000/

services:
  wxchat:
    # yilan666/wxchat:5.0
    image: registry.lazycat.cloud/czyt/yilan666/wxchat:5b15c3a307eb03ce
    container_name: wxchat
    ports:
      - "3000:3000"

    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/uploads:/app/uploads

    environment:
      - NODE_ENV=production
        # 服务端口号，默认3000
      - PORT=3000

        # 数据库配置
        # SQLite数据库文件路径（容器内路径）
      - DATABASE_PATH=/app/data/wxchat.db

        # 文件存储配置
        # 文件上传存储路径（容器内路径）
      - UPLOAD_PATH=/app/uploads

        # 安全配置（重要：生产环境必须修改）
        # 访问密码：用于登录系统，请修改为强密码
      - ACCESS_PASSWORD={{.U.access_password}}

        # JWT密钥：用于生成和验证访问令牌，请使用随机字符串
      - JWT_SECRET={{ stable_secret "wx#Chat" }}

        # 会话配置
        # 会话过期时间（小时），默认24小时
      - SESSION_EXPIRE_HOURS=24

        # 最大登录尝试次数，超过后需要等待
      - MAX_LOGIN_ATTEMPTS=5

        # 文件上传配置
        # 最大文件上传大小（MB），默认100MB
      - MAX_FILE_SIZE_MB=100

        # AI功能配置

        # 聊天功能配置
      - AI_ENABLED={{.U.ai_enabled}}
      - AI_CHAT_BASE_URL={{.U.ai_chat_base_url}}
      - AI_CHAT_API_KEY={{.U.ai_chat_api_key}}
      - AI_CHAT_MODEL={{.U.ai_chat_model}}
        # AI聊天请求限制（每分钟最大请求数）
      - AI_RATE_LIMIT={{.U.ai_rate_limit}}
        # 图片生成功能配置
      - IMAGE_GEN_ENABLED={{.U.image_gen_enabled}}
      - AI_IMAGE_BASE_URL={{.U.ai_image_base_url}}
      - AI_IMAGE_API_KEY={{.U.ai_image_api_key}}
      - AI_IMAGE_MODEL={{.U.ai_image_model}}
        # 图片生成请求限制（每分钟最大请求数）
      - IMAGE_RATE_LIMIT={{.U.image_rate_limit}}

locales:
  zh:
    name: "文件传输助手"
    description: "类微信文件传输助手，能像微信聊天一样在手机、电脑、平板之间快速互传文件、图片、文字和链接。需要的话还可接入大模型做 AI 聊天/ 画图。 "
  en:
    name: "File Transfer"
    description: "WeChat-like file transfer assistant, which can quickly transfer files, pictures, text, and links between mobile phones, computers, and tablets like WeChat chat. If needed, you can also access the large model for AI chat/drawing."
